### ISSUE TITLE
SQL Example

### ISSUE THREAD

**Issue by zeeoale** [Kr1SEl/destiny2TelegramBot#1]
can you add a sample SQL file for use the bot?

**Comment by Kr1SEl** [comment]
Hello, sorry for that long answer. Unfortunately I have no SQL file as I'm using PostgreSQL hosted on Heroku. You can use these settings on your .env file to connect your DB: 

# DATABASE
dbHost = '***'
dbName = '***'
dbUser = '***'
dbPort = '***'
dbPassword = '***'

All these setting may be found on Heroku in case you are using their host, or may be set by you if you're creating a DB on your local machine (for example using Docker)

In case you are asking about how database is look like - here as an example

<img width="780" alt="Screenshot 2022-09-03 at 17 19 50" src="https://user-images.githubusercontent.com/59517688/188277207-46b8a238-1cd5-44cd-9589-8dade8f745b6.png">
